### ISSUE TITLE
ACL validation error detail missing from output

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi-tailscale#19]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When updating an `Acl` resource with invalid configuration, the current output from the resource is:

```
  tailscale:index:Acl (main):
    error: 1 error occurred:
    	* updating urn:pulumi:production-tailscale::tailscale::tailscale:index/acl:Acl::main: 1 error occurred:
    	* Failed to set ACL: test(s) failed (400)
```

The API provides more detail than this about the specific elements of the ACL document that were invalid. It would be appreciated if these could be included in the output 🙏🏻

**Comment by jkodroff** [comment]
@shousper Thanks for submitting this issue.

This behavior is controlled in the upstream provider, https://github.com/davidsbond/terraform-provider-tailscale.

Here's the error message: https://github.com/davidsbond/terraform-provider-tailscale/blob/master/tailscale/resource_acl.go#L112

And here's the code that assembles the error: https://github.com/davidsbond/terraform-provider-tailscale/blob/b16a9258c3f76fb0028088e4ed3955718ba48ac0/tailscale/provider.go#L68-L76

I suggest submitting an issue (or PR if you're feeling inspired) upstream. If you submit the upstream issue, please comment so we can link the two issues.

**Comment by davidsbond** [comment]
Hey folks, I've just seen this issue, I'll whip up a fix.

**Comment by shousper** [comment]
Greatly appreciated @davidsbond 🙏🏻

**Comment by stack72** [comment]
Thank you so much @davidsbond!!!

**Comment by davidsbond** [comment]
No stress folks, @shousper I'm not sure how the output will look when done via pulumi, but any further problems do not be afraid to raise an issue on the terraform provider
