### ISSUE TITLE
Existing Teraform state

### ISSUE THREAD

**Issue by vafanassieff** [pulumi/pulumi-tailscale#208]
### What happened?

Hey i'm trying to update my ACL with Pulumi, i used to do it with Teraform.

When i'm running `pulumi up` i'm getting the folowing error

```
  error: 1 error occurred:
        * Failed to set ACL: ! You seem to be trying to overwrite a non-default ACL with a tailscale_acl resource.
    Before doing this, please import your existing ACL into Terraform state using:
     terraform import $(this_resource) acl
    (got error "precondition failed, invalid old hash (412)")
```

### Expected Behavior

Update the ACL on Tailscale

### Steps to reproduce

Create ACL with Teraform and update it with Pulumi

### Output of `pulumi about`
```
CLI          
Version      3.80.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME       VERSION
aws        6.0.4
aws        5.42.0
awsx       1.0.5
docker     3.6.1
nodejs     unknown
tailscale  0.13.0

Host     
OS       darwin
Version  13.5.1
Arch     arm64

This project is written in nodejs: executable='/Users/afa/Library/Caches/fnm_multishells/91529_1694014115126/bin/node' version='v18.16.1'

Current Stack: itoam/itoam/infra

TYPE                        URN
pulumi:pulumi:Stack         urn:pulumi:infra::itoam::pulumi:pulumi:Stack::itoam-infra
pulumi:providers:aws        urn:pulumi:infra::itoam::pulumi:providers:aws::default_6_0_4
pulumi:providers:tailscale  urn:pulumi:infra::itoam::pulumi:providers:tailscale::default_0_13_0
aws:route53/zone:Zone       urn:pulumi:infra::itoam::aws:route53/zone:Zone::itoam.dev


Found no pending operations associated with itoam/infra

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/vafanassieff
User           vafanassieff
Organizations  vafanassieff, itoam
```

### Additional context

```
  "dependencies": {
    "@pulumi/aws": "6.0.4",
    "@pulumi/awsx": "1.0.5",
    "@pulumi/pulumi": "3.80.0",
    "@pulumi/tailscale": "0.13.0"
  },
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @vafanassieff I'm sorry for the issue and especially for the confusing error message.

The crust of it seems to be correct though: since you are trying to bring an existing cloud resource under Pulumi management, you need to import it first into your Pulumi stack: https://www.pulumi.com/docs/using-pulumi/adopting-pulumi/import/

Could you give that a try and let me know if that resolves your issue?

**Comment by vafanassieff** [comment]
Thanks for your quick answer !

No need to be sorry, thanks for pointing me to this section of Pulumi documentation, i managed to import the state using this command :

`pulumi import tailscale:index/acl:Acl acl acl`

And then copied the code inside my typescript file.

I had to find the exact resource name in this repository

Best !
