### ISSUE TITLE
Pulumit tailscale contacts tailscale service withiut reason

### ISSUE THREAD

**Issue by nierob** [pulumi/pulumi-tailscale#358]
### What happened?

Seems that tailscale provider contacts tailscale even if there is no need to. That means no "refresh". It validates tokens, even if in theory those should not be in use.

The use case is important if pulumi controls full dependency tree and not everyone have access to  all admin keys. Right now the only workaround is to call pulumi with `--target`.

### Example

Running:
```sh
TAILSCALE_API_KEY=tskey-api-abc  pulumi --cwd infrastructure/pulumi --stack "production" up --diff
```

with simple resource:
```python
tailscale.Acl(
        "tailscale-acl",
        acl=tailscale_acl_path.read_text(),
        opts=p.ResourceOptions(protect=True),
    )
 ```
Causes tailscale provider to contact tailscale service. At least it fails with:

```
API token invalid (401)
```
and while the key is invalid, the provider should never need to know about it, because it was not told to **refresh** the state.

I would expect tailscale provider validate the pulumi state only and work kind of "offline" if  nothing changed.

### Output of `pulumi about`

pulumi output:
```
CLI
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Host
OS       debian
Version  trixie/sid
Arch     x86_64
```

### Additional context

```
pulumi plugin ls | grep tailscale                                                    0.315s (deploy) 11:40
tailscale     resource  0.15.0   39 MB   1 day ago     36 seconds ago
tailscale     resource  0.14.0   39 MB   1 week ago    36 seconds ago
tailscale     resource  0.13.4   38 MB   4 weeks ago   36 seconds ago
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @nierob. This is pretty common behavior for cloud providers. In your specific scenario, [tailscale/terraform-provider-tailscale](https://github.com/tailscale/terraform-provider-tailscale) (which this provider is based on) validates that the [ACL is valid](https://github.com/tailscale/terraform-provider-tailscale/blob/81416426406d54d41b140c6075de3aa325bfd4c2/tailscale/resource_acl.go#L44) as part of deciding if an action should be taken. This requires a valid token.

**Comment by nierob** [comment]
> Hi @nierob. This is pretty common behavior for cloud providers. In your specific scenario, [tailscale/terraform-provider-tailscale](https://github.com/tailscale/terraform-provider-tailscale) (which this provider is based on) validates that the [ACL is valid](https://github.com/tailscale/terraform-provider-tailscale/blob/81416426406d54d41b140c6075de3aa325bfd4c2/tailscale/resource_acl.go#L44) as part of deciding if an action should be taken. This requires a valid token.

But that is the point, as long pulumi state is the only source of information, ACL validation is influential. I could understand the behavior if I would call `pulumi up --refresh`, then sure ACL needs to be validated and generally the service needs to be contacted, but it happens without the refresh flag.

**Comment by nierob** [comment]
> I agree in spirit, however this provider is based on a provider authored by tailscale, so my bias is to respect what they do. They are the authority in their product.
> 
> If they change where ACL validation happens, we will follow their lead.

Ok, I will try to bring it there.
