### ISSUE TITLE
Upgrade provider to 0.5.1

### ISSUE THREAD

**Issue by davidsbond** [pulumi/pulumi-tailscale#4]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Hey folks, thanks for deciding my terraform provider was good enough to include in the pulumi registry, that's awesome. Just wanted to give you an FYI that the latest version is now 0.5.1 and includes some new resources/fields that users might find useful.

**Comment by stack72** [comment]
Thanks @davidsbond 

We will get it upgraded today :) Thanks so much!

**Comment by davidsbond** [comment]
No problem @stack72, mind if I ask the motivation for adding it to the pulumi registry? I pretty much built the provider for myself originally, and have ended up with multiple contributors and projects like this off the back of it. Are people internally at pulumi using the provider? Just always interested to hear how people are using it.
