### ISSUE TITLE
Can a OAuth Credential be created with this?

### ISSUE THREAD

**Issue by brentshulman-silkline** [pulumi/pulumi-tailscale#487]
I want to generate a Tailscale OAuth credential in Pulumi. Is there a way to do this right now? 

I see that you can create a Tailscale API Key, but I was hoping to generate an OAuth Client

**Comment by mjeffryes** [comment]
Unfortunately, not at this time. There's an [open issue](https://github.com/tailscale/terraform-provider-tailscale/issues/283) for this feature on the terraform provider (which this provider is derived from). From the discussion there, it sounds like this is ultimately blocked until tailscale adds an API for creating OAuth clients:[FR: Allow creating new OAuth clients using the API· tailscale/9632](https://github.com/tailscale/tailscale/issues/9632)
