### ISSUE TITLE
Downstream (forked) provider behind official(?) provider

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi-tailscale#84]
### What happened?

It looks like the Terraform provider this Pulumi provider is based on is a fork from the [Tailscale maintained](https://github.com/tailscale/terraform-provider-tailscale) provider, which is now more up to date than davidsbond's fork??

These updates would be appreciated 🙏🏻

I'm reporting this as a bug, because we're getting some weird behaviour with the Pulumi provider that could be resolved by those updates. I can provide detail of the bug though.

When an API Key expires, and one performs a `pulumi up`, Pulumi doesn't report any errors but accepts the changes into state regardless. Attempting for perform a `pulumi refresh` reveals the problem via a 401 response.

Once a new API Key is created and configured for use, a `pulumi refresh` (to correct invalid state) will report a 401 as well -- I assume because it's trying to use the expired API key from within the state? Performing a `pulumi up`, while it may list no changes to be applied, must be applied to update the API key in state. Then one can `pulumi refresh` to correct the Pulumi state.

### Steps to reproduce

- Apply some changes with a valid API key.
- Wait for the key to expire (or perhaps revoking it will behave the same way?)
- Try to apply some more changes, observe no errors reported and state is updated.
- Log into Tailscale console to find they're not applied.
- Run `pulumi refresh`, see 401 errors.
- Replace API key with fresh one.
- Run `pulumi refresh` to still see 401 errors.
- Run `pulumi up` and apply no changes.
- Run `pulumi refresh` to see corrections to state.
- Run `pulumi up` to apply changes properly.

### Expected Behavior

Should report 401 errors during `pulumi up` if API key has expired.

### Actual Behavior

Silently fails and assumes changes were made, committing them to pulumi state incorrectly.

### Output of `pulumi about`

```
CLI
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.10.0
cloudflare  3.6.0
command     0.3.2
eks         0.41.2
kubernetes  3.20.2
nodejs      unknown
random      4.8.1
tailscale   0.10.2
tailscale   0.10.2

Host
OS       darwin
Version  12.6
Arch     x86_64

This project is written in nodejs: executable='/Users/cmcgregor/.asdf/shims/node' version='v14.19.2'

Current Stack: production-tailscale

TYPE                                           URN
pulumi:pulumi:Stack                            urn:pulumi:production-tailscale::tailscale::pulumi:pulumi:Stack::tailscale-production-tailscale
pulumi:providers:tailscale                     urn:pulumi:production-tailscale::tailscale::pulumi:providers:tailscale::default_0_10_2
tailscale:index/dnsNameservers:DnsNameservers  urn:pulumi:production-tailscale::tailscale::tailscale:index/dnsNameservers:DnsNameservers::main
tailscale:index/dnsPreferences:DnsPreferences  urn:pulumi:production-tailscale::tailscale::tailscale:index/dnsPreferences:DnsPreferences::main
tailscale:index/acl:Acl                        urn:pulumi:production-tailscale::tailscale::tailscale:index/acl:Acl::main


Found no pending operations associated with production-tailscale
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
Thanks for opening the issue. I have updated our upstream tracker to the tailscale org instead: https://github.com/pulumi/pulumi-tailscale/pull/85. It doesn't look like there has been a new release of that provider though. We will update once a new release of the terraform provider is released.
