### ISSUE TITLE
Upgrade terraform-provider-tailscale to v0.13.6

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-tailscale#88]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by thomas11** [comment]
We should investigate why pulumi-bot didn't automatically such an issue, like #77 @t0yv0 @guineveresaenger

**Comment by jkodroff** [comment]
@thomas11 @guineveresaenger @t0yv0  It's because Zapier was set to track the wrong upstream. I believe I fixed it.
