### ISSUE TITLE
"xyz" from the original boilerplate still appears in the registry

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-tailscale#89]
### What happened?

The main registry page still contains the text "xyz" from the original boilerplate repo (likely sourced from schema.json): https://www.pulumi.com/registry/packages/tailscale/api-docs/ 

Additional instances (also probably from the same source): https://github.com/search?q=repo%3Apulumi%2Fpulumi-tailscale%20xyz&type=code

### Steps to reproduce

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
i thought i got all of these, thx for the report, will fix!

**Comment by susanev** [comment]
ha i did fix this https://github.com/pulumi/pulumi-tailscale/pull/87
it just hasn't merged or had a new release
